---
# tasks file for eucalyptus-clc

- include: packages.yml
  when: (ansible_os_family == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")
  become: yes

- include: init.yml
  when: (ansible_os_family == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")
  become: yes
